import type {
  Entity,
  Recommendation,
  ReconciliationItem,
  RiskAlert,
  ActionEvent,
} from "./types";

export const seedEntities: Entity[] = [
  {
    id: "ent-001",
    name: "Ministry of Health",
    type: "Ministry",
    sector: "Health",
    region: "National",
    budgetTzsB: 1240,
    riskLevel: "High",
    riskScore: 78,
    openRecommendations: 42,
    closedRecommendations: 118,
    reconciliationGapsTzsB: 3.2,
    lastAudit: "2025-11-14",
    contactName: "Dr. Amina Juma",
    contactEmail: "a.juma@moh.go.tz",
    dataConnections: ["IFMIS", "HRIS", "Payroll"],
    createdAt: "2023-01-12",
  },
  {
    id: "ent-002",
    name: "Ministry of Works & Transport",
    type: "Ministry",
    sector: "Infrastructure",
    region: "National",
    budgetTzsB: 2840,
    riskLevel: "Critical",
    riskScore: 88,
    openRecommendations: 61,
    closedRecommendations: 94,
    reconciliationGapsTzsB: 8.7,
    lastAudit: "2025-09-30",
    contactName: "Eng. Peter Msomba",
    contactEmail: "p.msomba@mowt.go.tz",
    dataConnections: ["IFMIS", "Procurement"],
    createdAt: "2023-01-12",
  },
  {
    id: "ent-003",
    name: "Ministry of Education, Science & Technology",
    type: "Ministry",
    sector: "Education",
    region: "National",
    budgetTzsB: 1580,
    riskLevel: "Moderate",
    riskScore: 54,
    openRecommendations: 28,
    closedRecommendations: 161,
    reconciliationGapsTzsB: 1.1,
    lastAudit: "2025-12-02",
    contactName: "Prof. Grace Mwinuka",
    contactEmail: "g.mwinuka@moest.go.tz",
    dataConnections: ["IFMIS", "HRIS"],
    createdAt: "2023-01-12",
  },
  {
    id: "ent-004",
    name: "Ministry of Agriculture",
    type: "Ministry",
    sector: "Agriculture",
    region: "National",
    budgetTzsB: 720,
    riskLevel: "Moderate",
    riskScore: 49,
    openRecommendations: 22,
    closedRecommendations: 88,
    reconciliationGapsTzsB: 0.9,
    lastAudit: "2025-10-18",
    contactName: "Hon. Ismail Chenge",
    contactEmail: "i.chenge@agri.go.tz",
    dataConnections: ["IFMIS"],
    createdAt: "2023-01-12",
  },
  {
    id: "ent-005",
    name: "TANROADS",
    type: "Agency",
    sector: "Infrastructure",
    region: "National",
    budgetTzsB: 1890,
    riskLevel: "High",
    riskScore: 74,
    openRecommendations: 39,
    closedRecommendations: 120,
    reconciliationGapsTzsB: 4.3,
    lastAudit: "2025-11-22",
    contactName: "Eng. Rose Lyimo",
    contactEmail: "r.lyimo@tanroads.go.tz",
    dataConnections: ["IFMIS", "Procurement", "Project MIS"],
    createdAt: "2023-01-12",
  },
  {
    id: "ent-006",
    name: "Dar es Salaam City Council",
    type: "LGA",
    sector: "Public Administration",
    region: "Coast",
    budgetTzsB: 410,
    riskLevel: "Moderate",
    riskScore: 58,
    openRecommendations: 18,
    closedRecommendations: 67,
    reconciliationGapsTzsB: 1.6,
    lastAudit: "2025-12-10",
    contactName: "Fatuma Said",
    contactEmail: "f.said@dcc.go.tz",
    dataConnections: ["LGRCIS", "IFMIS"],
    createdAt: "2023-01-12",
  },
  {
    id: "ent-007",
    name: "Mwanza City Council",
    type: "LGA",
    sector: "Public Administration",
    region: "Lake",
    budgetTzsB: 180,
    riskLevel: "High",
    riskScore: 71,
    openRecommendations: 24,
    closedRecommendations: 54,
    reconciliationGapsTzsB: 2.1,
    lastAudit: "2025-10-02",
    contactName: "John Magoti",
    contactEmail: "j.magoti@mcc.go.tz",
    dataConnections: ["LGRCIS"],
    createdAt: "2023-01-12",
  },
  {
    id: "ent-008",
    name: "Dodoma Capital Development Authority",
    type: "Public Authority",
    sector: "Infrastructure",
    region: "Capital",
    budgetTzsB: 260,
    riskLevel: "Low",
    riskScore: 31,
    openRecommendations: 6,
    closedRecommendations: 41,
    reconciliationGapsTzsB: 0.2,
    lastAudit: "2026-01-20",
    contactName: "Arch. Neema Ulaya",
    contactEmail: "n.ulaya@cda.go.tz",
    dataConnections: ["IFMIS"],
    createdAt: "2023-01-12",
  },
  {
    id: "ent-009",
    name: "Tanzania Revenue Authority",
    type: "Agency",
    sector: "Finance",
    region: "National",
    budgetTzsB: 480,
    riskLevel: "Low",
    riskScore: 28,
    openRecommendations: 9,
    closedRecommendations: 172,
    reconciliationGapsTzsB: 0.4,
    lastAudit: "2026-02-05",
    contactName: "CPA Yusuph Ngalo",
    contactEmail: "y.ngalo@tra.go.tz",
    dataConnections: ["IFMIS", "eFiling", "Customs"],
    createdAt: "2023-01-12",
  },
  {
    id: "ent-010",
    name: "TANESCO",
    type: "Public Authority",
    sector: "Energy",
    region: "National",
    budgetTzsB: 2110,
    riskLevel: "High",
    riskScore: 72,
    openRecommendations: 34,
    closedRecommendations: 98,
    reconciliationGapsTzsB: 5.2,
    lastAudit: "2025-08-28",
    contactName: "Eng. Said Mkumbwa",
    contactEmail: "s.mkumbwa@tanesco.co.tz",
    dataConnections: ["ERP", "Billing"],
    createdAt: "2023-01-12",
  },
  {
    id: "ent-011",
    name: "DAWASA",
    type: "Public Authority",
    sector: "Water",
    region: "Coast",
    budgetTzsB: 340,
    riskLevel: "Moderate",
    riskScore: 52,
    openRecommendations: 14,
    closedRecommendations: 63,
    reconciliationGapsTzsB: 1.0,
    lastAudit: "2025-11-05",
    contactName: "Eng. Lydia Kilaba",
    contactEmail: "l.kilaba@dawasa.go.tz",
    dataConnections: ["ERP"],
    createdAt: "2023-01-12",
  },
  {
    id: "ent-012",
    name: "Arusha District Council",
    type: "LGA",
    sector: "Public Administration",
    region: "North",
    budgetTzsB: 95,
    riskLevel: "Moderate",
    riskScore: 46,
    openRecommendations: 11,
    closedRecommendations: 38,
    reconciliationGapsTzsB: 0.6,
    lastAudit: "2025-12-19",
    contactName: "Baraka Mollel",
    contactEmail: "b.mollel@arushadc.go.tz",
    dataConnections: ["LGRCIS"],
    createdAt: "2023-01-12",
  },
];

export const seedRecommendations: Recommendation[] = [
  {
    id: "rec-1001",
    entityId: "ent-002",
    title: "Resolve duplicate contractor payments on Dar-Chalinze expressway",
    severity: "Critical",
    status: "Overdue",
    owner: "Director of Finance, MoWT",
    dueDate: "2026-02-28",
    createdDate: "2025-08-14",
    description:
      "Three duplicate payments totalling TZS 2.4B identified across Q3 2025. Recovery plan requested.",
  },
  {
    id: "rec-1002",
    entityId: "ent-001",
    title: "Reconcile drug procurement variance in 14 regional hospitals",
    severity: "High",
    status: "In Progress",
    owner: "Chief Internal Auditor, MoH",
    dueDate: "2026-05-15",
    createdDate: "2025-10-02",
    description:
      "Central warehouse dispatch records do not match hospital receiving logs for essential medicines.",
  },
  {
    id: "rec-1003",
    entityId: "ent-005",
    title: "Close payroll ghost worker gap in 3 regional offices",
    severity: "High",
    status: "Open",
    owner: "Director of HR, TANROADS",
    dueDate: "2026-06-30",
    createdDate: "2025-11-22",
    description:
      "28 accounts with no biometric verification continue to draw salaries. Full headcount audit required.",
  },
  {
    id: "rec-1004",
    entityId: "ent-010",
    title: "Publish project completion certificates for Mwalimu Nyerere dam",
    severity: "Medium",
    status: "In Progress",
    owner: "Project Director, TANESCO",
    dueDate: "2026-07-12",
    createdDate: "2025-09-18",
    description: "Independent verification of works completion pending.",
  },
  {
    id: "rec-1005",
    entityId: "ent-006",
    title: "Strengthen revenue collection internal controls",
    severity: "Medium",
    status: "Implemented",
    owner: "City Treasurer, Dar CC",
    dueDate: "2026-01-31",
    createdDate: "2025-07-04",
    description: "Controls matrix redesigned. Quarterly independent review set up.",
  },
  {
    id: "rec-1006",
    entityId: "ent-007",
    title: "Address procurement split-order pattern flagged in 2024",
    severity: "High",
    status: "Overdue",
    owner: "Head of Procurement, Mwanza CC",
    dueDate: "2025-12-15",
    createdDate: "2025-04-22",
    description:
      "18 cases of procurement amounts just below competitive threshold identified.",
  },
  {
    id: "rec-1007",
    entityId: "ent-003",
    title: "Automate capitation grant disbursement reconciliation",
    severity: "Medium",
    status: "In Progress",
    owner: "Director of Policy, MoEST",
    dueDate: "2026-08-01",
    createdDate: "2025-11-11",
    description: "End-to-end match of disbursed vs received by each school.",
  },
  {
    id: "rec-1008",
    entityId: "ent-009",
    title: "Publish end-user satisfaction index for eFiling",
    severity: "Low",
    status: "Implemented",
    owner: "ICT Director, TRA",
    dueDate: "2026-03-31",
    createdDate: "2025-10-01",
    description: "Index published and linked in annual report.",
  },
  {
    id: "rec-1009",
    entityId: "ent-011",
    title: "Reduce non-revenue water reporting discrepancies",
    severity: "High",
    status: "Open",
    owner: "COO, DAWASA",
    dueDate: "2026-09-30",
    createdDate: "2026-02-18",
    description:
      "System-reported losses diverge from meter census by 7.2 percentage points.",
  },
  {
    id: "rec-1010",
    entityId: "ent-004",
    title: "Reconcile agricultural input subsidy distribution in Mbeya",
    severity: "Medium",
    status: "In Progress",
    owner: "PS, Ministry of Agriculture",
    dueDate: "2026-05-30",
    createdDate: "2025-12-12",
    description: "Registered beneficiaries vs distribution logs gap of 14%.",
  },
];

export const seedReconciliation: ReconciliationItem[] = [
  {
    id: "rcn-1",
    entityId: "ent-002",
    category: "Procurement",
    gapTzsB: 2.4,
    status: "Escalated",
    detectedDate: "2026-04-18",
    description: "Duplicate invoice numbers across 3 contractor payments.",
  },
  {
    id: "rcn-2",
    entityId: "ent-001",
    category: "Budget vs Expenditure",
    gapTzsB: 1.7,
    status: "Flagged",
    detectedDate: "2026-04-17",
    description:
      "Reported expenditure at facility level exceeds approved budget allocation.",
  },
  {
    id: "rcn-3",
    entityId: "ent-005",
    category: "Payroll",
    gapTzsB: 0.9,
    status: "Under Review",
    detectedDate: "2026-04-15",
    description: "Payroll total exceeds approved headcount × band midpoint.",
  },
  {
    id: "rcn-4",
    entityId: "ent-010",
    category: "Revenue",
    gapTzsB: 5.2,
    status: "Flagged",
    detectedDate: "2026-04-10",
    description: "Billed revenue vs collection deposit mismatch — 3 regions.",
  },
  {
    id: "rcn-5",
    entityId: "ent-011",
    category: "Treasury",
    gapTzsB: 0.7,
    status: "Cleared",
    detectedDate: "2026-04-05",
    description: "Bank reconciliation cleared after Q1 closing review.",
  },
  {
    id: "rcn-6",
    entityId: "ent-007",
    category: "Procurement",
    gapTzsB: 0.45,
    status: "Under Review",
    detectedDate: "2026-04-03",
    description: "Three-way match failed on 12 purchase orders.",
  },
  {
    id: "rcn-7",
    entityId: "ent-003",
    category: "Budget vs Expenditure",
    gapTzsB: 1.1,
    status: "Flagged",
    detectedDate: "2026-03-28",
    description: "Capitation grant received vs reported usage variance.",
  },
];

export const seedAlerts: RiskAlert[] = [
  {
    id: "alrt-1",
    title: "High duplicate payments risk",
    description: "Detected in 12 entities with linked supplier patterns.",
    level: "Critical",
    entitiesAffected: 12,
    detectedAt: "2026-04-21T09:12:00Z",
    type: "Duplicate Payment",
  },
  {
    id: "alrt-2",
    title: "Reconciliation gaps above TZS 1.7B",
    description: "Seven entities require urgent review and explanation.",
    level: "High",
    entitiesAffected: 7,
    detectedAt: "2026-04-21T08:45:00Z",
    type: "Reconciliation",
  },
  {
    id: "alrt-3",
    title: "Recommendation closure slowdown",
    description: "43 entities now past response threshold.",
    level: "High",
    entitiesAffected: 43,
    detectedAt: "2026-04-20T14:02:00Z",
    type: "Reporting Delay",
  },
  {
    id: "alrt-4",
    title: "Payroll anomaly cluster in Lake zone",
    description: "9 LGAs show headcount vs payroll drift > 3%.",
    level: "Moderate",
    entitiesAffected: 9,
    detectedAt: "2026-04-19T11:30:00Z",
    type: "Payroll Anomaly",
  },
  {
    id: "alrt-5",
    title: "Procurement split-order pattern",
    description:
      "18 procurements just below competitive threshold — Mwanza CC, Arusha DC.",
    level: "High",
    entitiesAffected: 2,
    detectedAt: "2026-04-18T17:14:00Z",
    type: "Procurement",
  },
];

export const seedActions: ActionEvent[] = [
  {
    id: "act-1",
    title: "Duplicate payments flagged in 12 entities",
    timeAgo: "2m ago",
    type: "flag",
  },
  {
    id: "act-2",
    title: "Reconciliation gaps above TZS 1.7B identified",
    timeAgo: "15m ago",
    type: "flag",
  },
  {
    id: "act-3",
    title: "43 overdue recommendations escalated",
    timeAgo: "1h ago",
    type: "escalation",
  },
  {
    id: "act-4",
    title: "Three ministries moved to enhanced audit watch",
    timeAgo: "Today",
    type: "update",
  },
  {
    id: "act-5",
    title: "Dar CC closed 7 recommendations — verified",
    timeAgo: "Today",
    type: "resolution",
  },
];

// Overall counters shown on the Command Centre sidebar / stats
export const baselineCounts = {
  ministries: 38,
  departments: 176,
  agencies: 256,
  publicAuthorities: 162,
  lgas: 241,
};

export const trendOfExceptions: { label: string; value: number }[] = [
  { label: "Nov", value: 412 },
  { label: "Dec", value: 388 },
  { label: "Jan", value: 421 },
  { label: "Feb", value: 468 },
  { label: "Mar", value: 445 },
  { label: "Apr", value: 391 },
];

export const recommendationImplementation = [
  { quarter: "Q2 25", open: 2310, closed: 1840 },
  { quarter: "Q3 25", open: 2480, closed: 2120 },
  { quarter: "Q4 25", open: 2610, closed: 2285 },
  { quarter: "Q1 26", open: 2456, closed: 2510 },
];

export const sectorIntensity = [
  { sector: "Health", intensity: 72 },
  { sector: "Infrastructure", intensity: 88 },
  { sector: "Education", intensity: 54 },
  { sector: "Agriculture", intensity: 48 },
  { sector: "Energy", intensity: 74 },
  { sector: "Water", intensity: 51 },
  { sector: "Finance", intensity: 29 },
];
